import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import clsx from "clsx";

const rubik = Rubik({
  display: "swap",
  subsets: ["latin"],
  variable: "---font-rubik",
  weight: ["400", "500", "600", "700"],
  preload: true,
});

const rift = localFont({
  src: [
    {
      path: "../assets/fonts/rift/rift-regular.woff2",
      weight: "400",
    },
    {
      path: "../assets/fonts/rift/rift-italic.woff2",
      style: "italic",
      weight: "400",
    },
    {
      path: "../assets/fonts/rift/rift-medium-italic.woff2",
      style: "italic",
      weight: "500",
    },
  ],
  variable: "--font-rift",
  preload: true,
});

export const metadata: Metadata = {
  title: "GH05TWRITER",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(rubik.variable, rift.variable)}>{children}</body>
    </html>
  );
}
